#:schema ./server-config5.schema.json

logStreams = ["console", "file"]

cdnUrl = "http://awdawd"

connectionQueue = true

[voice]
externalPublicHost = "xx.xx.xx.xx"

[worldProfiler]
host = "0.0.0.0"
port = 7797


[js-module]
profiler = true
inspector = {  }
